#!/data/data/com.termux/files/usr/bin/bash
echo "py repos with most stars since 10 days ago"
gh search repos "language:Python" \
  --sort stars \
  --order desc \
  --created ">$(date -d '10 days ago' +%Y-%m-%d)" \
  --limit 50
